/* Populating Hostels table */

INSERT INTO HOSTELS (HOSTEL_ID, HOSTEL_LOCATION, CAPACITY, HOSTEL_NAME)
VALUES (1, 'Main Campus, Karachi University', 200, 'Capt Haleem Siddiqui Boys Hostel');

INSERT INTO HOSTELS (HOSTEL_ID, HOSTEL_LOCATION, CAPACITY, HOSTEL_NAME)
VALUES (2, 'Main Campus, Karachi University', 150, 'Sir Anwar Pervez Boys Hostel');

INSERT INTO HOSTELS (HOSTEL_ID, HOSTEL_LOCATION, CAPACITY, HOSTEL_NAME)
VALUES (3, 'Main Campus, Karachi University', 150, 'IBA Girls Hostel');

INSERT INTO HOSTELS (HOSTEL_ID, HOSTEL_LOCATION, CAPACITY, HOSTEL_NAME)
VALUES (4, 'City Campus, Saddar', 50, 'IBA City Campus Hostel');


/* Populating Rooms Table */
 -- HOSTEL 1
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('101', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('102', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('103', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('104', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('105', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('106', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('107', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('108', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('109', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('110', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('111', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('112', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('113', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('114', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('115', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('116', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('117', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('118', 1, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('119', 1, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('120', 1, 'SINGLE', 'OCCUPIED');
-- Dorm Rooms (10)
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('201', 1, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('202', 1, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('203', 1, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('204', 1, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('205', 1, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('206', 1, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('207', 1, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('208', 1, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('209', 1, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('210', 1, 'DORM', 'OCCUPIED');

 -- HOSTEL 2
 -- Single Rooms for Hostel 2
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('201', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('202', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('203', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('204', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('205', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('206', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('207', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('208', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('209', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('210', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('211', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('212', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('213', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('214', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('215', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('216', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('217', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('218', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('219', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('220', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('221', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('222', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('223', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('224', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('225', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('226', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('227', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('228', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('229', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('230', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('231', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('232', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('233', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('234', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('235', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('236', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('237', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('238', 2, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('239', 2, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('240', 2, 'SINGLE', 'OCCUPIED');

-- Dorm Rooms for Hostel 2
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('301', 2, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('302', 2, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('303', 2, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('304', 2, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('305', 2, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('306', 2, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('307', 2, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('308', 2, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('309', 2, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('310', 2, 'DORM', 'OCCUPIED');

 -- HOSTEL 3
 -- Single Rooms for Hostel 3
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('301', 3, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('302', 3, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('303', 3, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('304', 3, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('305', 3, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('306', 3, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('307', 3, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('308', 3, 'SINGLE', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('309', 3, 'SINGLE', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('310', 3, 'SINGLE', 'OCCUPIED');

-- Dorm Rooms for Hostel 3 (80% = 40 rooms)
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('401', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('402', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('403', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('404', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('405', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('406', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('407', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('408', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('409', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('410', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('411', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('412', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('413', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('414', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('415', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('416', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('417', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('418', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('419', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('420', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('421', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('422', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('423', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('424', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('425', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('426', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('427', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('428', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('429', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('430', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('431', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('432', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('433', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('434', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('435', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('436', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('437', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('438', 3, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('439', 3, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('440', 3, 'DORM', 'OCCUPIED');

-- HOSTEL 4 
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('401', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('402', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('403', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('404', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('405', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('406', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('407', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('408', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('409', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('410', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('411', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('412', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('413', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('414', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('415', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('416', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('417', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('418', 4, 'DORM', 'UNOCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('419', 4, 'DORM', 'OCCUPIED');
INSERT INTO ROOMS (ROOM_NO, HOSTEL_ID, ROOM_TYPE, ROOM_STATUS) VALUES ('420', 4, 'DORM', 'UNOCCUPIED');

/*Populating Employees table */

/* There is only one superintendent */
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (1, 'Ali', 'Khan', 'Superintendent', 'ali.khan@iba.edu.pk', '03011234567');
select * from employees;

 -- HOSTEL 1
 -- Warden
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (2, 'Ahmed', 'Khan', 'Warden', 'ahmed.khan@iba.edu.pk', '03012345678');

-- Office Assistant
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (3, 'Tariq', 'Malik', 'Office Assistant', 'tariq.malik@iba.edu.pk', '03022334455');

-- Staff Supervisor
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (4, 'Nasir', 'Ali', 'Staff Supervisor', 'nasir.ali@iba.edu.pk', '03033334455');

-- Security Guards
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (5, 'Imran', 'Khan', 'Security Guard', 'imran.khan@iba.edu.pk', '03041234567');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (6, 'Aslam', 'Hussain', 'Security Guard', 'aslam.hussain@iba.edu.pk', '03042345678');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (7, 'Kamran', 'Ali', 'Security Guard', 'kamran.ali@iba.edu.pk', '03043456789');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (8, 'Sajid', 'Mehmood', 'Security Guard', 'sajid.mehmood@iba.edu.pk', '03044567890');

-- Cleaners
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (9, 'Faisal', 'Riaz', 'Cleaner', 'faisal.riaz@iba.edu.pk', '03055678901');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (10, 'Jamal', 'Qureshi', 'Cleaner', 'jamal.qureshi@iba.edu.pk', '03056789012');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (11, 'Muneeb', 'Ahmed', 'Cleaner', 'muneeb.ahmed@iba.edu.pk', '03055648901');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (12, 'Majid', 'Bhatti', 'Cleaner', 'majid.bhatti@iba.edu.pk', '03136789012');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (13, 'Karim', 'Obaid', 'Cleaner', 'karim.obaid@iba.edu.pk', '03132415901');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (14, 'Sagar', 'Kumar', 'Cleaner', 'sagar.kumar@iba.edu.pk', '03098539012');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (15, 'Hassan', 'Fasi', 'Cleaner', 'hassan.fasi@iba.edu.pk', '03095578901');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (16, 'Asad', 'Imran', 'Cleaner', 'asad.imran@iba.edu.pk', '03009837012');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (17, 'Shaheer', 'Zahid', 'Cleaner', 'shaheer.zahid@iba.edu.pk', '03787478901');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (18, 'Faeiz', 'Ahmed', 'Cleaner', 'faeiz.ahmed@iba.edu.pk', '03059099012');


-- Carpenters
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (19, 'Latif', 'Shah', 'Carpenter', 'latif.shah@iba.edu.pk', '03067890123');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (20, 'Saleem', 'Butt', 'Carpenter', 'saleem.butt@iba.edu.pk', '03078901234');

-- Electricians
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (21, 'Yasir', 'Ali', 'Electrician', 'yasir.ali@iba.edu.pk', '03089012345');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (22, 'Aqib', 'Javed', 'Electrician', 'aqib.javed@iba.edu.pk', '03090123456');

 --HOSTEL 3
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (23, 'Irfan', 'Amin', 'Warden', 'irfan.amin@iba.edu.pk', '03112233445');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (24, 'Imran', 'Shah', 'Office Assistant', 'imran.shah@iba.edu.pk', '03122334455');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (25, 'Khalid', 'Ansari', 'Staff Supervisor', 'khalid.ansari@iba.edu.pk', '03133445566');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (26, 'Usman', 'Ali', 'Security Guard', 'usman.ali@iba.edu.pk', '03144556677');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (27, 'Bilal', 'Shah', 'Security Guard', 'bilal.shah@iba.edu.pk', '03155667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (28, 'Rashid', 'Malik', 'Security Guard', 'rashid.malik@iba.edu.pk', '03166778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (29, 'Waqar', 'Hussain', 'Security Guard', 'waqar.hussain@iba.edu.pk', '03177889900');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (30, 'Adnan', 'Raza', 'Cleaner', 'adnan.raza@iba.edu.pk', '03188990011');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (31, 'Sohail', 'Ahmed', 'Cleaner', 'sohail.ahmed@iba.edu.pk', '03199001122');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (32, 'Asif', 'Bukhari', 'Cleaner', 'asif.bukhari@iba.edu.pk', '03200112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (33, 'Naveed', 'Shaikh', 'Cleaner', 'naveed.shaikh@iba.edu.pk', '03211223344');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (34, 'Shahid', 'Ali', 'Cleaner', 'shahid.ali@iba.edu.pk', '03222334455');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (35, 'Irfan', 'Zubair', 'Cleaner', 'irfan.zubair@iba.edu.pk', '03233445566');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (36, 'Hassan', 'Riaz', 'Cleaner', 'hassan.riaz@iba.edu.pk', '03244556677');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (37, 'Javed', 'Iqbal', 'Cleaner', 'javed.iqbal@iba.edu.pk', '03255667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (38, 'Muneer', 'Ahmed', 'Cleaner', 'muneer.ahmed@iba.edu.pk', '03266778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (39, 'Kamran', 'Ali', 'Cleaner', 'kamran.ali@iba.edu.pk', '03277889900');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (40, 'Azhar', 'Saeed', 'Carpenter', 'azhar.saeed@iba.edu.pk', '03288990011');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (41, 'Tanveer', 'Hassan', 'Carpenter', 'tanveer.hassan@iba.edu.pk', '03299001122');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (42, 'Fahad', 'Ali', 'Electrician', 'fahad.ali@iba.edu.pk', '03300112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (43, 'Qasim', 'Mehmood', 'Electrician', 'qasim.mehmood@iba.edu.pk', '03311223344');

 -- HOSTEL 3
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (44, 'Ayesha', 'Khan', 'Warden', 'ayesha.khan@iba.edu.pk', '03312233445');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (45, 'Fatima', 'Ansari', 'Office Assistant', 'fatima.ansari@iba.edu.pk', '03322334455');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (46, 'Nazia', 'Malik', 'Staff Supervisor', 'nazia.malik@iba.edu.pk', '03333445566');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (47, 'Ibrahim', 'Shah', 'Security Guard', 'ibrahim.shah@iba.edu.pk', '03344556677');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (48, 'Rizwan', 'Ali', 'Security Guard', 'rizwan.ali@iba.edu.pk', '03355667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (49, 'Adil', 'Mehmood', 'Security Guard', 'adil.mehmood@iba.edu.pk', '03366778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (50, 'Noman', 'Qureshi', 'Security Guard', 'noman.qureshi@iba.edu.pk', '03377889900');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (51, 'Sania', 'Ahmed', 'Cleaner', 'sania.ahmed@iba.edu.pk', '03388990011');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (52, 'Rabia', 'Shah', 'Cleaner', 'rabia.shah@iba.edu.pk', '03399001122');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (53, 'Hina', 'Bukhari', 'Cleaner', 'hina.bukhari@iba.edu.pk', '03400112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (54, 'Asma', 'Shaikh', 'Cleaner', 'asma.shaikh@iba.edu.pk', '03411223344');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (55, 'Farah', 'Ali', 'Cleaner', 'farah.ali@iba.edu.pk', '03422334455');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (56, 'Mariam', 'Zubair', 'Cleaner', 'mariam.zubair@iba.edu.pk', '03433445566');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (57, 'Zara', 'Riaz', 'Cleaner', 'zara.riaz@iba.edu.pk', '03444556677');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (58, 'Amina', 'Iqbal', 'Cleaner', 'amina.iqbal@iba.edu.pk', '03455667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (59, 'Saba', 'Ahmed', 'Cleaner', 'saba.ahmed@iba.edu.pk', '03466778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (60, 'Fiza', 'Ali', 'Cleaner', 'fiza.ali@iba.edu.pk', '03477889900');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (61, 'Junaid', 'Saeed', 'Carpenter', 'junaid.saeed@iba.edu.pk', '03488990011');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (62, 'Adeel', 'Hassan', 'Carpenter', 'adeel.hassan@iba.edu.pk', '03499001122');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (63, 'Salman', 'Ali', 'Electrician', 'salman.ali@iba.edu.pk', '03500112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (64, 'Hassan', 'Mehmood', 'Electrician', 'hassan.mehmood@iba.edu.pk', '03511223344');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (65, 'Ali', 'Khan', 'Warden', 'ali.khan@iba.edu.pk', '03522334455');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (66, 'Bilal', 'Ali', 'Office Assistant', 'bilal.ali@iba.edu.pk', '03533445566');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (67, 'Zubair', 'Ahmed', 'Staff Supervisor', 'zubair.ahmed@iba.edu.pk', '03544556677');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (68, 'Omar', 'Raza', 'Security Guard', 'omar.raza@iba.edu.pk', '03555667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (69, 'Bilal', 'Shah', 'Security Guard', 'bilal.shah@iba.edu.pk', '03566778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (70, 'Tariq', 'Mehmood', 'Security Guard', 'tariq.mehmood@iba.edu.pk', '03577889900');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (71, 'Fahad', 'Ali', 'Security Guard', 'fahad.ali@iba.edu.pk', '03588990011');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (72, 'Ahmed', 'Raza', 'Cleaner', 'ahmed.raza@iba.edu.pk', '03599001122');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (73, 'Usman', 'Shah', 'Cleaner', 'usman.shah@iba.edu.pk', '03600112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (74, 'Omar', 'Ali', 'Cleaner', 'omar.ali@iba.edu.pk', '03611223344');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (75, 'Nashit', 'Iqbal', 'Cleaner', 'nashit.iqbal@iba.edu.pk', '03622334455');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (76, 'Muneeb', 'Hassan', 'Cleaner', 'muneeb.hassan@iba.edu.pk', '03633445566');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (77, 'Sohail', 'Bukhari', 'Cleaner', 'sohail.bukhari@iba.edu.pk', '03644556677');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (78, 'Farhan', 'Shah', 'Cleaner', 'farhan.shah@iba.edu.pk', '03655667788');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (79, 'Hassan', 'Raza', 'Cleaner', 'hassan.raza@iba.edu.pk', '03666778899');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (80, 'Ali', 'Iqbal', 'Cleaner', 'ali.iqbal@iba.edu.pk', '03677889900');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (81, 'Shahbaz', 'Khan', 'Cleaner', 'shahbaz.khan@iba.edu.pk', '03688990011');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (82, 'Adeel', 'Hassan', 'Carpenter', 'adeel.hassan@iba.edu.pk', '03700112233');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (83, 'Raza', 'Shah', 'Carpenter', 'raza.shah@iba.edu.pk', '03711223344');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (84, 'Salman', 'Saeed', 'Electrician', 'salman.saeed@iba.edu.pk', '03722334455');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, E_FIRST_NAME, E_LAST_NAME, DESIGNATION, E_EMAIL, E_CONTACT_NO) 
VALUES (85, 'Ali', 'Raza', 'Electrician', 'ali.raza@iba.edu.pk', '03733445566');

/* Populalting Residents table */


    -- HOSTEL 1
    -- Resident 1 (Room 2 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1001, 1, 2, 'Ahmed', 'Khan', 'BS CS', 2023, 'ahmed.khan@iba.edu.pk', '03331234567', 'Ali Khan', 'Father', '03123456789');

    -- Resident 2 (Room 4 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1002, 1, 4, 'Bilal', 'Ahmed', 'BS ACF', 2024, 'bilal.ahmed@iba.edu.pk', '03341234567', 'Raza Ahmed', 'Uncle', '03213456789');

    -- Resident 3 (Room 6 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1003, 1, 6, 'Fahad', 'Raza', 'PHD', 2024, 'fahad.raza@iba.edu.pk', '03371234567', 'Ghulam Raza', 'Father', '03134567890');

    -- Resident 4 (Room 8 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1004, 1, 8, 'Omer', 'Farooq', 'MS DE', 2025, 'omer.farooq@iba.edu.pk', '03391234567', 'Jameel Farooq', 'Father', '03256789012');

    -- Resident 5 (Room 10 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1005, 1, 10, 'Omar', 'Shah', 'BS ECO', 2024, 'omar.shah@iba.edu.pk', '03421234567', 'Zahid Shah', 'Father', '03290123456');

    -- Resident 6 (Room 12 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1006, 1, 12, 'Ali', 'Iqbal', 'MS ECO', 2025, 'ali.iqbal@iba.edu.pk', '03451234567', 'Zahid Iqbal', 'Father', '03292345678');

    -- Resident 7 (Room 14 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1007, 1, 14, 'Shahbaz', 'Khan', 'MBA', 2023, 'shahbaz.khan@iba.edu.pk', '03461234567', 'Shamshad Khan', 'Father', '03293456789');

    -- Resident 8 (Room 16 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1008, 1, 16, 'Zain', 'Ahmad', 'BS CS', 2024, 'zain.ahmad@iba.edu.pk', '03471234567', 'Rashid Ahmad', 'Father', '03295678901');

    -- Resident 9 (Room 18 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1009, 1, 18, 'Ali', 'Bukhari', 'BS ACF', 2025, 'ali.bukhari@iba.edu.pk', '03481234567', 'Faisal Bukhari', 'Father', '03296543210');

    -- Resident 10 (Room 20 - Single)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1010, 1, 20, 'Tariq', 'Iqbal', 'MS DS', 2024, 'tariq.iqbal@iba.edu.pk', '03491234567', 'Khalid Iqbal', 'Father', '03287654321');

    -- Resident 11 (Room 22 - Dorm, 2 residents)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1011, 1, 22, 'Sohail', 'Bukhari', 'BS SS', 2023, 'sohail.bukhari@iba.edu.pk', '03501234567', 'Shafique Bukhari', 'Father', '03298765432');
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1012, 1, 22, 'Farhan', 'Hassan', 'BS MATH', 2024, 'farhan.hassan@iba.edu.pk', '03511234567', 'Ali Hassan', 'Father', '03299876543');

    -- Resident 12 (Room 24 - Dorm, 2 residents)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1013, 1, 24, 'Ahmed', 'Shah', 'MS ECO', 2023, 'ahmed.shah@iba.edu.pk', '03521234567', 'Sultan Shah', 'Father', '03298765421');
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1014, 1, 24, 'Fahad', 'Khan', 'MS DS', 2024, 'fahad.khan@iba.edu.pk', '03531234567', 'Tariq Khan', 'Father', '03297654321');

    -- Resident 13 (Room 26 - Dorm, 2 residents)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1015, 1, 26, 'Saad', 'Iqbal', 'BS ECO', 2023, 'saad.iqbal@iba.edu.pk', '03541234567', 'Shahzad Iqbal', 'Father', '03296765432');
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1016, 1, 26, 'Nashit', 'Khan', 'BS ACF', 2024, 'nashit.khan@iba.edu.pk', '03551234567', 'Faisal Khan', 'Father', '03298876543');

    -- Resident 14 (Room 28 - Dorm, 2 residents)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1017, 1, 28, 'Muneeb', 'Raza', 'MBA', 2023, 'muneeb.raza@iba.edu.pk', '03561234567', 'Shafiq Raza', 'Father', '03297865432');
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1018, 1, 28, 'Shahbaz', 'Ali', 'BS CS', 2024, 'shahbaz.ali@iba.edu.pk', '03571234567', 'Muneeb Ali', 'Father', '03298976543');

    -- Resident 15 (Room 30 - Dorm, 2 residents)
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
    VALUES (1019, 1, 30, 'Shahram', 'Bukhari', 'BS ECO', 2023, 'shahram.bukhari@iba.edu.pk', '03581234567', 'Gulzar Bukhari', 'Father', '03297765432');
    INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER)
    VALUES (1020, 1, 30, 'Zain', 'Imtiaz', 'BS ECO', 2023, 'zain.imtiaz@iba.edu.pk', '03002329817', 'Imtiaz Ahmed', 'Father', '03142591287');

    -- HOSTEL 2
    -- Insert records for single rooms in Hostel 2 (Boys Hostel)
INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1021, 2, 32, 'Hassan', 'Raza', 'BS CS', 2024, 'hassan.raza@iba.edu.pk', '03591234567', 'Ibrahim Raza', 'Father', '03298765432');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1022, 2, 34, 'Ahsan', 'Farooq', 'MS DS', 2025, 'ahsan.farooq@iba.edu.pk', '03591234568', 'Jameel Farooq', 'Father', '03298765433');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1023, 2, 36, 'Zain', 'Ali', 'BS ACF', 2023, 'zain.ali@iba.edu.pk', '03591234569', 'Sami Ali', 'Father', '03298765434');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1024, 2, 38, 'Farhan', 'Iqbal', 'BS ECO', 2024, 'farhan.iqbal@iba.edu.pk', '03591234570', 'Rashid Iqbal', 'Father', '03298765435');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1025, 2, 40, 'Shahzad', 'Javed', 'MS DE', 2025, 'shahzad.javed@iba.edu.pk', '03591234571', 'Sultan Javed', 'Father', '03298765436');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1026, 2, 42, 'Bilal', 'Khattak', 'BBA', 2024, 'bilal.khattak@iba.edu.pk', '03591234572', 'Zahid Khattak', 'Father', '03298765437');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1027, 2, 44, 'Rizwan', 'Mehmood', 'BS MATH', 2023, 'rizwan.mehmood@iba.edu.pk', '03591234573', 'Imtiaz Mehmood', 'Father', '03298765438');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1028, 2, 46, 'Hamza', 'Bashir', 'BS ACF', 2024, 'hamza.bashir@iba.edu.pk', '03591234574', 'Irfan Bashir', 'Father', '03298765439');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1029, 2, 48, 'Kashan', 'Siddique', 'MS DS', 2025, 'kashan.siddique@iba.edu.pk', '03591234575', 'Nawaz Siddique', 'Father', '03298765440');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1030, 2, 50, 'Owais', 'Rehman', 'BBA', 2024, 'owais.rehman@iba.edu.pk', '03591234576', 'Sajid Rehman', 'Father', '03298765441');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1031, 2, 52, 'Muneeb', 'Aziz', 'BS ECO', 2023, 'muneeb.aziz@iba.edu.pk', '03591234577', 'Raza Aziz', 'Father', '03298765442');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1032, 2, 54, 'Usman', 'Nawaz', 'MS DE', 2024, 'usman.nawaz@iba.edu.pk', '03591234578', 'Yousaf Nawaz', 'Father', '03298765443');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1033, 2, 56, 'Adeel', 'Shahzad', 'BS ACF', 2025, 'adeel.shahzad@iba.edu.pk', '03591234579', 'Zulfiqar Shahzad', 'Father', '03298765444');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1034, 2, 58, 'Shahrukh', 'Saeed', 'BBA', 2024, 'shahrukh.saeed@iba.edu.pk', '03591234580', 'Khalid Saeed', 'Father', '03298765445');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1035, 2, 60, 'Tariq', 'Hussain', 'MS DS', 2023, 'tariq.hussain@iba.edu.pk', '03591234581', 'Nasir Hussain', 'Father', '03298765446');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1036, 2, 62, 'Arslan', 'Mirza', 'BS CS', 2024, 'arslan.mirza@iba.edu.pk', '03591234582', 'Faisal Mirza', 'Father', '03298765447');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1037, 2, 64, 'Saad', 'Latif', 'BBA', 2025, 'saad.latif@iba.edu.pk', '03591234583', 'Shahid Latif', 'Father', '03298765448');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1038, 2, 66, 'Bilal', 'Hussain', 'BS CS', 2024, 'bilal.hussain@iba.edu.pk', '03591234584', 'Anwar Hussain', 'Father', '03298765449');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1039, 2, 68, 'Omar', 'Rafiq', 'MS DS', 2025, 'omar.rafiq@iba.edu.pk', '03591234585', 'Shafiq Rafiq', 'Father', '03298765450');
INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER)
VALUES (1040, 2, 70, 'Naveed', 'Qureshi', 'MS DE', 2024, 'naveed.qureshi@iba.edu.pk', '03391234520', 'Safia Qureshi', 'Mother', '03191234520');

-- Insert records for dorms in Hostel 2 (Boys Hostel)

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1040, 2, 72, 'Tariq', 'Rashid', 'BBA', 2024, 'tariq.rashid@iba.edu.pk', '03591234586', 'Shahbaz Rashid', 'Father', '03298765451');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1041, 2, 74, 'Zeeshan', 'Siddique', 'MS DS', 2023, 'zeeshan.siddique@iba.edu.pk', '03591234587', 'Tariq Siddique', 'Father', '03298765452');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1042, 2, 76, 'Jameel', 'Khan', 'BS ACF', 2024, 'jameel.khan@iba.edu.pk', '03591234588', 'Fawad Khan', 'Father', '03298765453');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1043, 2, 78, 'Sohail', 'Anwar', 'BBA', 2024, 'sohail.anwar@iba.edu.pk', '03591234589', 'Salim Anwar', 'Father', '03298765454');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1044, 2, 80, 'Ahmed', 'Yousaf', 'BS MATH', 2025, 'ahmed.yousaf@iba.edu.pk', '03591234590', 'Riaz Yousaf', 'Father', '03298765455');

INSERT INTO RESIDENTS (ERP_ID, HOSTEL_ID, ROOM_ID, R_FIRST_NAME, R_LAST_NAME, PROGRAM, BATCH, CONTACT_INFO_EMAIL, CONTACT_INFO_NUMBER, EMERGENCY_CONTACT_NAME, EMERGENCY_CONTACT_RELATION, EMERGENCY_CONTACT_NUMBER) 
VALUES (1044, 2, 70, 'Omer', 'Qureshi', 'BS CS', 2024, 'omer.qureshi@iba.edu.pk', '03591234591', 'Tariq Qureshi', 'Father', '03298765456');

-- Dorm 72
INSERT INTO RESIDENTS VALUES (1041, 2, 72, 'Yasir', 'Khan', 'PHD', 2025, 'yasir.khan@iba.edu.pk', '03391234521', 'Akbar Khan', 'Father', '03191234521');
INSERT INTO RESIDENTS VALUES (1042, 2, 72, 'Aadil', 'Ahmed', 'BS SS', 2023, 'aadil.ahmed@iba.edu.pk', '03391234522', 'Aziz Ahmed', 'Father', '03191234522');

-- Dorm 74
INSERT INTO RESIDENTS VALUES (1043, 2, 74, 'Talha', 'Shah', 'BS CS', 2024, 'talha.shah@iba.edu.pk', '03391234523', 'Rehman Shah', 'Father', '03191234523');
INSERT INTO RESIDENTS VALUES (1044, 2, 74, 'Hashim', 'Iqbal', 'BS ACF', 2025, 'hashim.iqbal@iba.edu.pk', '03391234524', 'Idrees Iqbal', 'Father', '03191234524');

-- Dorm 76
INSERT INTO RESIDENTS VALUES (1045, 2, 76, 'Rizwan', 'Raza', 'BS MATH', 2023, 'rizwan.raza@iba.edu.pk', '03391234525', 'Khalid Raza', 'Father', '03191234525');
INSERT INTO RESIDENTS VALUES (1046, 2, 76, 'Noman', 'Farooq', 'BBA', 2024, 'noman.farooq@iba.edu.pk', '03391234526', 'Zubair Farooq', 'Father', '03191234526');

-- Dorm 78
INSERT INTO RESIDENTS VALUES (1047, 2, 78, 'Farrukh', 'Ali', 'BS ECO', 2025, 'farrukh.ali@iba.edu.pk', '03391234527', 'Mazhar Ali', 'Father', '03191234527');
INSERT INTO RESIDENTS VALUES (1048, 2, 78, 'Saad', 'Hassan', 'BS BIO', 2023, 'saad.hassan@iba.edu.pk', '03391234528', 'Shahid Hassan', 'Father', '03191234528');

-- Dorm 80
INSERT INTO RESIDENTS VALUES (1049, 2, 80, 'Zubair', 'Siddiqui', 'MS DS', 2024, 'zubair.siddiqui@iba.edu.pk', '03391234529', 'Arif Siddiqui', 'Father', '03191234529');
INSERT INTO RESIDENTS VALUES (1050, 2, 80, 'Javed', 'Qureshi', 'MBA', 2025, 'javed.qureshi@iba.edu.pk', '03391234530', 'Ghulam Qureshi', 'Father', '03191234530');

 -- HOSTEL 3
-- ERP_ID=1051 (1051 mod 3=1 → BATCH=2023)
INSERT INTO RESIDENTS VALUES (1051, 3, 82, 'Sara', 'Khan', 'BS CS', 2023, 'sara.khan@iba.edu.pk', '03392210001', 'Amir Khan', 'Father', '03192210001');

-- ERP_ID=1052 (mod 3=2 → BATCH=2024)
INSERT INTO RESIDENTS VALUES (1052, 3, 84, 'Ayesha', 'Ali', 'BBA', 2024, 'ayesha.ali@iba.edu.pk', '03392210002', 'Rehan Ali', 'Father', '03192210002');

-- ERP_ID=1053 (mod 3=0 → BATCH=2025)
INSERT INTO RESIDENTS VALUES (1053, 3, 86, 'Hina', 'Siddiqui', 'MS DS', 2025, 'hina.siddiqui@iba.edu.pk', '03392210003', 'Nadeem Siddiqui', 'Father', '03192210003');

-- ERP_ID=1054 (mod 3=1 → BATCH=2023)
INSERT INTO RESIDENTS VALUES (1054, 3, 88, 'Fatima', 'Farooq', 'BS ECO', 2023, 'fatima.farooq@iba.edu.pk', '03392210004', 'Khalid Farooq', 'Father', '03192210004');

-- ERP_ID=1055 (mod 3=2 → BATCH=2024)
INSERT INTO RESIDENTS VALUES (1055, 3, 90, 'Marium', 'Raza', 'BS ACF', 2024, 'marium.raza@iba.edu.pk', '03392210005', 'Zahir Raza', 'Father', '03192210005');

-- 1056 (mod 3=0 → 2025) Program: BS CS (first in cycle)
INSERT INTO RESIDENTS VALUES (1056, 3, 92, 'Alina', 'Ali', 'BS CS', 2025, 'alina.ali@iba.edu.pk', '03392210006', 'Nadia Ali', 'Mother', '03192210006');

-- 1057 (mod 3=1 →2023) next program: BBA
INSERT INTO RESIDENTS VALUES (1057, 3, 92, 'Mahnoor', 'Siddiqui', 'BBA', 2023, 'mahnoor.siddiqui@iba.edu.pk', '03392210007', 'Zahida Siddiqui', 'Mother', '03192210007');

-- 1058 (mod 3=2→2024) BS ECO
INSERT INTO RESIDENTS VALUES (1058, 3, 94, 'Sana', 'Farooq', 'BS ECO', 2024, 'sana.farooq@iba.edu.pk', '03392210008', 'Lubna Farooq', 'Mother', '03192210008');

-- 1059 (mod 3=0→2025) MS DS
INSERT INTO RESIDENTS VALUES (1059, 3, 94, 'Rabia', 'Raza', 'MS DS', 2025, 'rabia.raza@iba.edu.pk', '03392210009', 'Sabeen Raza', 'Mother', '03192210009');

INSERT INTO RESIDENTS VALUES (1060, 3, 96, 'Zara', 'Iqbal', 'BS ACF', 2023, 'zara.iqbal@iba.edu.pk', '03392210010', 'Hina Iqbal', 'Mother', '03192210010');

INSERT INTO RESIDENTS VALUES (1061, 3, 96, 'Hira', 'Shah', 'MS DE', 2024, 'hira.shah@iba.edu.pk', '03392210011', 'Nadia Shah', 'Mother', '03192210011');

INSERT INTO RESIDENTS VALUES (1062, 3, 98, 'Nadia', 'Qureshi', 'PHD', 2025, 'nadia.qureshi@iba.edu.pk', '03392210012', 'Zahida Qureshi', 'Mother', '03192210012');

INSERT INTO RESIDENTS VALUES (1063, 3, 98, 'Anum', 'Ahmed', 'BS SS', 2023, 'anum.ahmed@iba.edu.pk', '03392210013', 'Lubna Ahmed', 'Mother', '03192210013');

INSERT INTO RESIDENTS VALUES (1064, 3, 100, 'Samina', 'Khan', 'BS MATH', 2024, 'samina.khan@iba.edu.pk', '03392210014', 'Sabeen Khan', 'Mother', '03192210014');

INSERT INTO RESIDENTS VALUES (1065, 3, 100, 'Maryam', 'Ali', 'BS BIO', 2025, 'maryam.ali@iba.edu.pk', '03392210015', 'Hina Ali', 'Mother', '03192210015');

INSERT INTO RESIDENTS VALUES (1066, 3, 102, 'Aleeza', 'Siddiqui', 'MBA', 2023, 'aleeza.siddiqui@iba.edu.pk', '03392210016', 'Nadia Siddiqui', 'Mother', '03192210016');

INSERT INTO RESIDENTS VALUES (1067, 3, 102, 'Zainab', 'Farooq', 'BS CS', 2024, 'zainab.farooq@iba.edu.pk', '03392210017', 'Zahida Farooq', 'Mother', '03192210017');

INSERT INTO RESIDENTS VALUES (1068, 3, 104, 'Huma', 'Raza', 'BBA', 2025, 'huma.raza@iba.edu.pk', '03392210018', 'Lubna Raza', 'Mother', '03192210018');

INSERT INTO RESIDENTS VALUES (1069, 3, 104, 'Noor', 'Iqbal', 'BS ECO', 2023, 'noor.iqbal@iba.edu.pk', '03392210019', 'Sabeen Iqbal', 'Mother', '03192210019');

INSERT INTO RESIDENTS VALUES (1070, 3, 106, 'Aisha', 'Shah', 'MS DS', 2024, 'aisha.shah@iba.edu.pk', '03392210020', 'Hina Shah', 'Mother', '03192210020');

INSERT INTO RESIDENTS VALUES (1071, 3, 106, 'Mehak', 'Qureshi', 'BS ACF', 2025, 'mehak.qureshi@iba.edu.pk', '03392210021', 'Nadia Qureshi', 'Mother', '03192210021');

INSERT INTO RESIDENTS VALUES (1072, 3, 108, 'Sadia', 'Ahmed', 'MS DE', 2023, 'sadia.ahmed@iba.edu.pk', '03392210022', 'Zahida Ahmed', 'Mother', '03192210022');

INSERT INTO RESIDENTS VALUES (1073, 3, 108, 'Maliha', 'Khan', 'PHD', 2024, 'maliha.khan@iba.edu.pk', '03392210023', 'Lubna Khan', 'Mother', '03192210023');

INSERT INTO RESIDENTS VALUES (1074, 3, 110, 'Rida', 'Ali', 'BS SS', 2025, 'rida.ali@iba.edu.pk', '03392210024', 'Sabeen Ali', 'Mother', '03192210024');

INSERT INTO RESIDENTS VALUES (1075, 3, 110, 'Hafsa', 'Siddiqui', 'BS MATH', 2023, 'hafsa.siddiqui@iba.edu.pk', '03392210025', 'Hina Siddiqui', 'Mother', '03192210025');

INSERT INTO RESIDENTS VALUES (1076, 3, 112, 'Anisha', 'Farooq', 'BS BIO', 2024, 'anisha.farooq@iba.edu.pk', '03392210026', 'Nadia Farooq', 'Mother', '03192210026');

INSERT INTO RESIDENTS VALUES (1077, 3, 112, 'Ifra', 'Raza', 'MBA', 2025, 'ifra.raza@iba.edu.pk', '03392210027', 'Zahida Raza', 'Mother', '03192210027');

INSERT INTO RESIDENTS VALUES (1078, 3, 114, 'Aqsa', 'Iqbal', 'BS CS', 2023, 'aqsa.iqbal@iba.edu.pk', '03392210028', 'Lubna Iqbal', 'Mother', '03192210028');

INSERT INTO RESIDENTS VALUES (1079, 3, 114, 'Sabeen', 'Shah', 'BBA', 2024, 'sabeen.shah@iba.edu.pk', '03392210029', 'Sakina Shah ', 'Mother', '03192210029'); 

INSERT INTO RESIDENTS VALUES (1080, 3, 116, 'Fareeha', 'Qureshi', 'BS ECO', 2025, 'fareeha.qureshi@iba.edu.pk', '03392210030', 'Hina Qureshi', 'Mother', '03192210030');

INSERT INTO RESIDENTS VALUES (1081, 3, 116, 'Zaina', 'Ahmed', 'MS DS', 2023, 'zaina.ahmed@iba.edu.pk', '03392210031', 'Nadia Ahmed', 'Mother', '03192210031');

INSERT INTO RESIDENTS VALUES (1082, 3, 118, 'Laiba', 'Khan', 'BS ACF', 2024, 'laiba.khan@iba.edu.pk', '03392210032', 'Zahida Khan', 'Mother', '03192210032');

INSERT INTO RESIDENTS VALUES (1083, 3, 118, 'Maira', 'Ali', 'MS DE', 2025, 'maira.ali@iba.edu.pk', '03392210033', 'Lubna Ali', 'Mother', '03192210033');

INSERT INTO RESIDENTS VALUES (1084, 3, 120, 'Emaan', 'Siddiqui', 'PHD', 2023, 'emaan.siddiqui@iba.edu.pk', '03392210034', 'Sabeen Siddiqui', 'Mother', '03192210034');

INSERT INTO RESIDENTS VALUES (1085, 3, 120, 'Aleena', 'Farooq', 'BS SS', 2024, 'aleena.farooq@iba.edu.pk', '03392210035', 'Hina Farooq', 'Mother', '03192210035');

INSERT INTO RESIDENTS VALUES (1086, 3, 122, 'Nimra', 'Raza', 'BS MATH', 2025, 'nimra.raza@iba.edu.pk', '03392210036', 'Nadia Raza', 'Mother', '03192210036');

INSERT INTO RESIDENTS VALUES (1087, 3, 122, 'Fiza', 'Iqbal', 'BS BIO', 2023, 'fiza.iqbal@iba.edu.pk', '03392210037', 'Zahida Iqbal', 'Mother', '03192210037');

INSERT INTO RESIDENTS VALUES (1088, 3, 124, 'Tania', 'Shah', 'MBA', 2024, 'tania.shah@iba.edu.pk', '03392210038', 'Lubna Shah', 'Mother', '03192210038');

INSERT INTO RESIDENTS VALUES (1089, 3, 124, 'Sahar', 'Qureshi', 'BS CS', 2025, 'sahar.qureshi@iba.edu.pk', '03392210039', 'Sabeen Qureshi', 'Mother', '03192210039');

INSERT INTO RESIDENTS VALUES (1090, 3, 126, 'Arooj', 'Ahmed', 'BBA', 2023, 'arooj.ahmed@iba.edu.pk', '03392210040', 'Hina Ahmed', 'Mother', '03192210040');

INSERT INTO RESIDENTS VALUES (1091, 3, 126, 'Warda', 'Khan', 'BS ECO', 2024, 'warda.khan@iba.edu.pk', '03392210041', 'Nadia Khan', 'Mother', '03192210041');

INSERT INTO RESIDENTS VALUES (1092, 3, 128, 'Aiman', 'Ali', 'MS DS', 2025, 'aiman.ali@iba.edu.pk', '03392210042', 'Zahida Ali', 'Mother', '03192210042');

INSERT INTO RESIDENTS VALUES (1093, 3, 128, 'Hiba', 'Siddiqui', 'BS ACF', 2023, 'hiba.siddiqui@iba.edu.pk', '03392210043', 'Lubna Siddiqui', 'Mother', '03192210043');

INSERT INTO RESIDENTS VALUES (1094, 3, 130, 'Mishal', 'Farooq', 'MS DE', 2024, 'mishal.farooq@iba.edu.pk', '03392210044', 'Sabeen Farooq', 'Mother', '03192210044');

INSERT INTO RESIDENTS VALUES (1095, 3, 130, 'Yusra', 'Raza', 'PHD', 2025, 'yusra.raza@iba.edu.pk', '03392210045', 'Hina Raza', 'Mother', '03192210045');

 -- HOSTEL 4
INSERT INTO RESIDENTS VALUES (1096, 4, 131, 'Ali', 'Khan', 'BS CS', 2023, 'ali.khan@iba.edu.pk', '03393220001', 'Tariq Khan', 'Father', '03193220001');
INSERT INTO RESIDENTS VALUES (1097, 4, 131, 'Ahmed', 'Ali', 'BBA', 2024, 'ahmed.ali@iba.edu.pk', '03393220002', 'Tariq Ali', 'Father', '03193220002');
INSERT INTO RESIDENTS VALUES (1098, 4, 133, 'Bilal', 'Raza', 'BS ECO', 2025, 'bilal.raza@iba.edu.pk', '03393220003', 'Tariq Raza', 'Father', '03193220003');
INSERT INTO RESIDENTS VALUES (1099, 4, 133, 'Umar', 'Iqbal', 'MS DS', 2023, 'umar.iqbal@iba.edu.pk', '03393220004', 'Tariq Iqbal', 'Father', '03193220004');
INSERT INTO RESIDENTS VALUES (1100, 4, 135, 'Faisal', 'Farooq', 'BS ACF', 2024, 'faisal.farooq@iba.edu.pk', '03393220005', 'Tariq Farooq', 'Father', '03193220005');
INSERT INTO RESIDENTS VALUES (1101, 4, 135, 'Zain', 'Siddiqui', 'MS DE', 2025, 'zain.siddiqui@iba.edu.pk', '03393220006', 'Tariq Siddiqui', 'Father', '03193220006');
INSERT INTO RESIDENTS VALUES (1102, 4, 137, 'Imran', 'Qureshi', 'PHD', 2023, 'imran.qureshi@iba.edu.pk', '03393220007', 'Tariq Qureshi', 'Father', '03193220007');
INSERT INTO RESIDENTS VALUES (1103, 4, 137, 'Owais', 'Ahmed', 'BS SS', 2024, 'owais.ahmed@iba.edu.pk', '03393220008', 'Tariq Ahmed', 'Father', '03193220008');
INSERT INTO RESIDENTS VALUES (1104, 4, 139, 'Kamran', 'Shah', 'BS MATH', 2025, 'kamran.shah@iba.edu.pk', '03393220009', 'Tariq Shah', 'Father', '03193220009');
INSERT INTO RESIDENTS VALUES (1105, 4, 139, 'Shoaib', 'Khan', 'BS BIO', 2023, 'shoaib.khan@iba.edu.pk', '03393220010', 'Tariq Khan', 'Father', '03193220010');
INSERT INTO RESIDENTS VALUES (1106, 4, 141, 'Adeel', 'Ali', 'MBA', 2024, 'adeel.ali@iba.edu.pk', '03393220011', 'Tariq Ali', 'Father', '03193220011');
INSERT INTO RESIDENTS VALUES (1107, 4, 141, 'Hassan', 'Raza', 'BS CS', 2025, 'hassan.raza@iba.edu.pk', '03393220012', 'Tariq Raza', 'Father', '03193220012');
INSERT INTO RESIDENTS VALUES (1108, 4, 143, 'Rizwan', 'Iqbal', 'BBA', 2023, 'rizwan.iqbal@iba.edu.pk', '03393220013', 'Tariq Iqbal', 'Father', '03193220013');
INSERT INTO RESIDENTS VALUES (1109, 4, 143, 'Yousuf', 'Farooq', 'BS ECO', 2024, 'yousuf.farooq@iba.edu.pk', '03393220014', 'Tariq Farooq', 'Father', '03193220014');
INSERT INTO RESIDENTS VALUES (1110, 4, 145, 'Arslan', 'Siddiqui', 'MS DS', 2025, 'arslan.siddiqui@iba.edu.pk', '03393220015', 'Tariq Siddiqui', 'Father', '03193220015');
INSERT INTO RESIDENTS VALUES (1111, 4, 145, 'Shahbaz', 'Qureshi', 'BS ACF', 2023, 'shahbaz.qureshi@iba.edu.pk', '03393220016', 'Tariq Qureshi', 'Father', '03193220016');
INSERT INTO RESIDENTS VALUES (1112, 4, 147, 'Muneeb', 'Ahmed', 'MS DE', 2024, 'muneeb.ahmed@iba.edu.pk', '03393220017', 'Tariq Ahmed', 'Father', '03193220017');
INSERT INTO RESIDENTS VALUES (1113, 4, 147, 'Farhan', 'Khan', 'PHD', 2025, 'farhan.khan@iba.edu.pk', '03393220018', 'Tariq Khan', 'Father', '03193220018');
INSERT INTO RESIDENTS VALUES (1114, 4, 149, 'Noman', 'Ali', 'BS SS', 2023, 'noman.ali@iba.edu.pk', '03393220019', 'Tariq Ali', 'Father', '03193220019');
INSERT INTO RESIDENTS VALUES (1115, 4, 149, 'Zeeshan', 'Raza', 'BS MATH', 2024, 'zeeshan.raza@iba.edu.pk', '03393220020', 'Tariq Raza', 'Father', '03193220020');

/* Populating Employee Assignments */
-- Superintendent for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    1, 1, 'Superintendent', TO_DATE('2023-02-15', 'YYYY-MM-DD')
);

-- Superintendent for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    1, 2, 'Superintendent', TO_DATE('2023-04-10', 'YYYY-MM-DD')
);

-- Superintendent for Hostel 3
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    1, 3, 'Superintendent', TO_DATE('2023-06-05', 'YYYY-MM-DD')
);

-- Superintendent for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    1, 4, 'Superintendent', TO_DATE('2023-08-20', 'YYYY-MM-DD')
);

-- Warden for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    2, 1, 'Warden', TO_DATE('2023-03-01', 'YYYY-MM-DD')
);

-- Warden for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    65, 2, 'Warden', TO_DATE('2023-05-15', 'YYYY-MM-DD')
);

-- Warden for Hostel 3 (Female)
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    44, 3, 'Warden', TO_DATE('2023-07-10', 'YYYY-MM-DD')
);

-- Warden for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    23, 4, 'Warden', TO_DATE('2023-09-05', 'YYYY-MM-DD')
);

-- Office Assistant for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    3, 1, 'Office Assistant', TO_DATE('2023-02-20', 'YYYY-MM-DD')
);

-- Office Assistant for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    66, 2, 'Office Assistant', TO_DATE('2023-04-25', 'YYYY-MM-DD')
);

-- Office Assistant for Hostel 3 (Female)
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    45, 3, 'Office Assistant', TO_DATE('2023-07-15', 'YYYY-MM-DD')
);

-- Office Assistant for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    24, 4, 'Office Assistant', TO_DATE('2023-09-15', 'YYYY-MM-DD')
);

-- Staff Supervisor for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    4, 1, 'Staff Supervisor', TO_DATE('2023-03-10', 'YYYY-MM-DD')
);

-- Staff Supervisor for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    67, 2, 'Staff Supervisor', TO_DATE('2023-05-20', 'YYYY-MM-DD')
);

-- Staff Supervisor for Hostel 3 (Female)
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    46, 3, 'Staff Supervisor', TO_DATE('2023-07-20', 'YYYY-MM-DD')
);

-- Staff Supervisor for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    25, 4, 'Staff Supervisor', TO_DATE('2023-09-20', 'YYYY-MM-DD')
);

-- Cleaners for Hostel 1
BEGIN
    FOR emp_id IN 9..18 LOOP
        INSERT INTO EMPLOYEE_ASSIGNMENTS (
            EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
        ) VALUES (
            emp_id, 1, 'Cleaner', TO_DATE('2023-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,12)), 2, '0') || '-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,28)), 2, '0'), 'YYYY-MM-DD')
        );
    END LOOP;
END;
/

-- Cleaners for Hostel 2
BEGIN
    FOR emp_id IN 72..81 LOOP
        INSERT INTO EMPLOYEE_ASSIGNMENTS (
            EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
        ) VALUES (
            emp_id, 2, 'Cleaner', TO_DATE('2023-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,12)), 2, '0') || '-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,28)), 2, '0'), 'YYYY-MM-DD')
        );
    END LOOP;
END;
/

-- Cleaners for Hostel 3
BEGIN
    FOR emp_id IN 51..60 LOOP
        INSERT INTO EMPLOYEE_ASSIGNMENTS (
            EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
        ) VALUES (
            emp_id, 3, 'Cleaner', TO_DATE('2023-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,12)), 2, '0') || '-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,28)), 2, '0'), 'YYYY-MM-DD')
        );
    END LOOP;
END;
/

-- Cleaners for Hostel 4
BEGIN
    FOR emp_id IN 30..39 LOOP
        INSERT INTO EMPLOYEE_ASSIGNMENTS (
            EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
        ) VALUES (
            emp_id, 4, 'Cleaner', TO_DATE('2023-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,12)), 2, '0') || '-' || LPAD(FLOOR(DBMS_RANDOM.VALUE(1,28)), 2, '0'), 'YYYY-MM-DD')
        );
    END LOOP;
END;
/

-- Carpenters for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    19, 1, 'Carpenter', TO_DATE('2023-03-05', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    20, 1, 'Carpenter', TO_DATE('2023-03-10', 'YYYY-MM-DD')
);

-- Carpenters for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    40, 2, 'Carpenter', TO_DATE('2023-05-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    41, 2, 'Carpenter', TO_DATE('2023-06-01', 'YYYY-MM-DD')
);

-- Carpenters for Hostel 3
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    61, 3, 'Carpenter', TO_DATE('2023-07-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    62, 3, 'Carpenter', TO_DATE('2023-08-01', 'YYYY-MM-DD')
);

-- Carpenters for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    82, 4, 'Carpenter', TO_DATE('2023-09-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    83, 4, 'Carpenter', TO_DATE('2023-10-01', 'YYYY-MM-DD')
);

-- Electricians for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    21, 1, 'Electrician', TO_DATE('2023-03-15', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    22, 1, 'Electrician', TO_DATE('2023-03-20', 'YYYY-MM-DD')
);

-- Electricians for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    84, 2, 'Electrician', TO_DATE('2023-05-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    85, 2, 'Electrician', TO_DATE('2023-06-01', 'YYYY-MM-DD')
);

-- Electricians for Hostel 3
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    42, 3, 'Electrician', TO_DATE('2023-07-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    43, 3, 'Electrician', TO_DATE('2023-08-01', 'YYYY-MM-DD')
);

-- Electricians for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    63, 4, 'Electrician', TO_DATE('2023-09-25', 'YYYY-MM-DD')
);
INSERT INTO EMPLOYEE_ASSIGNMENTS (
    EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE
) VALUES (
    64, 4, 'Electrician', TO_DATE('2023-10-01', 'YYYY-MM-DD')
);

-- Security Guards for Hostel 1
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (5, 1, 'Security Guard', TO_DATE('2023-01-15', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (6, 1, 'Security Guard', TO_DATE('2023-02-20', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (7, 1, 'Security Guard', TO_DATE('2023-03-10', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (8, 1, 'Security Guard', TO_DATE('2023-04-05', 'YYYY-MM-DD'));

-- Security Guards for Hostel 2
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (68, 2, 'Security Guard', TO_DATE('2023-05-12', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (69, 2, 'Security Guard', TO_DATE('2023-06-18', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (70, 2, 'Security Guard', TO_DATE('2023-07-25', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (71, 2, 'Security Guard', TO_DATE('2023-08-30', 'YYYY-MM-DD'));

-- Security Guards for Hostel 3
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (26, 3, 'Security Guard', TO_DATE('2023-09-15', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (27, 3, 'Security Guard', TO_DATE('2023-10-20', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (28, 3, 'Security Guard', TO_DATE('2023-11-25', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (29, 3, 'Security Guard', TO_DATE('2023-12-30', 'YYYY-MM-DD'));

-- Security Guards for Hostel 4
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (47, 4, 'Security Guard', TO_DATE('2023-10-05', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (48, 4, 'Security Guard', TO_DATE('2023-11-10', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (49, 4, 'Security Guard', TO_DATE('2023-12-15', 'YYYY-MM-DD'));
INSERT INTO EMPLOYEE_ASSIGNMENTS (EMPLOYEE_ID, HOSTEL_ID, ASSIGNED_ROLE, START_DATE) VALUES (50, 4, 'Security Guard', TO_DATE('2023-12-20', 'YYYY-MM-DD'));

select * from employees where designation = 'Cleaner'
order by employee_id;

-- Populating Payments table
-- People who have availed 3 meals (amount = 5000) and laundry services for the semester
BEGIN
    FOR resident_id IN 1001..1050 LOOP
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Mess', 5000.00);
        
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Laundry', 1500.00);
    END LOOP;
    COMMIT;
END;
/

-- People who have availed 2 meals (amount = 3500) and laundry services for the semester
BEGIN
    FOR resident_id IN 1051..1100 LOOP
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Mess', 3500.00);
        
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Laundry', 1500.00);
    END LOOP;
    COMMIT;
END;
/
-- People who have availed 1 meal (amount = 2000) and laundry services for the semester
BEGIN
    FOR resident_id IN 1101..1115 LOOP
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Mess', 2000.00);
        
        INSERT INTO PAYMENTS (ERP_ID, PAYMENT_TYPE, AMOUNT)
        VALUES (resident_id, 'Laundry', 1500.00);
    END LOOP;
    COMMIT;
END;
/

-- Populating Mess table

BEGIN
    FOR rec IN (
        SELECT P.PAYMENT_ID, P.ERP_ID, R.HOSTEL_ID, P.AMOUNT
        FROM PAYMENTS P LEFT JOIN RESIDENTS R ON P.ERP_ID=R.ERP_ID
        WHERE PAYMENT_TYPE = 'Mess'
    ) LOOP
        DECLARE
            v_meals NUMBER;
        BEGIN
            -- Determine number of meals based on amount
            IF rec.AMOUNT = 5000 THEN
                v_meals := 3;
            ELSIF rec.AMOUNT = 3500 THEN
                v_meals := 2;
            ELSIF rec.AMOUNT = 2000 THEN
                v_meals := 1;
            ELSE
                -- Handle unexpected amounts
                v_meals := NULL;
                DBMS_OUTPUT.PUT_LINE('Unexpected amount ' || rec.AMOUNT || ' for PAYMENT_ID ' || rec.PAYMENT_ID);
            END IF;
            
            -- Only insert if meals are determined
            IF v_meals IS NOT NULL THEN
                INSERT INTO MESS (
                    ERP_ID, HOSTEL_ID, MESS_PERIOD, MEALS, PAYMENT_ID
                ) VALUES (
                    rec.ERP_ID,
                    rec.HOSTEL_ID,
                    'November 2024',
                    v_meals,
                    rec.PAYMENT_ID
                );
            END IF;
        END;
    END LOOP;
    COMMIT;
END;
/

-- Populating Laundry Table
BEGIN
    FOR rec IN (
        SELECT P.PAYMENT_ID AS pay_id, P.ERP_ID AS erp, R.HOSTEL_ID AS hid, P.AMOUNT AS amt
        FROM PAYMENTS P
        LEFT JOIN RESIDENTS R ON P.ERP_ID = R.ERP_ID
        WHERE P.PAYMENT_TYPE = 'Laundry'
    ) LOOP
        INSERT INTO LAUNDRY (HOSTEL_ID, ERP_ID, LAUNDRY_PERIOD, PAYMENT_ID)
        VALUES (rec.hid, rec.erp, 'Fall 2024', rec.pay_id);
    END LOOP;
END;

-- Populating Common Areas Table

-- Hostel 1 Common Areas
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (20, 1, 'GYM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (21, 1, 'PRAYER ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (22, 1, 'MESS', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (23, 1, 'WASHROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (24, 1, 'WASHROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (25, 1, 'TV ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (26, 1, 'TV ROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (27, 1, 'TUCK SHOP', 'Available');

-- Hostel 2 Common Areas
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (28, 2, 'GYM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (29, 2, 'PRAYER ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (30, 2, 'MESS', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (31, 2, 'WASHROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (32, 2, 'WASHROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (33, 2, 'TV ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (34, 2, 'TV ROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (35, 2, 'TUCK SHOP', 'Available');

-- Hostel 3 Common Areas
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (36, 3, 'GYM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (37, 3, 'PRAYER ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (38, 3, 'MESS', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (39, 3, 'WASHROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (40, 3, 'WASHROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (41, 3, 'TV ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (42, 3, 'TV ROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (43, 3, 'TUCK SHOP', 'Available');

-- Hostel 4 Common Areas
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (44, 4, 'GYM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (45, 4, 'PRAYER ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (46, 4, 'MESS', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (47, 4, 'WASHROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (48, 4, 'WASHROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (49, 4, 'TV ROOM', 'Available');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (50, 4, 'TV ROOM', 'Under Maintenance');
INSERT INTO COMMON_AREAS (COMMON_AREA_ID, HOSTEL_ID, AREA_TYPE, AVAILABILITY) VALUES (51, 4, 'TUCK SHOP', 'Available');

-- Populating Inventory table

-- ===================== HOSTEL 1 INVENTORY =====================

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Chair', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Bed', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Side Table', 'Needs repairing/replacement');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Sofa', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Sofa', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Table', 'Needs repairing/replacement');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (1, 'Watercooler', 'Good');


-- ===================== HOSTEL 2 INVENTORY =====================

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Bed', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Sofa', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Sofa', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Table', 'Needs repairing/replacement');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (2, 'Watercooler', 'Good');

-- ===================== HOSTEL 3 INVENTORY =====================

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Bed', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Chair', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Side Table', 'Needs repairing/replacement');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Sofa', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Sofa', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Table', 'Needs repairing/replacement');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (3, 'Watercooler', 'Good');

-- ===================== HOSTEL 4 INVENTORY =====================

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Bed', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Chair', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Side Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Bed', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Chair', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Side Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Sofa', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Good');

INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'TV', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Sofa', 'Good');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Table', 'Needs repairing/replacement');
INSERT INTO INVENTORY (HOSTEL_ID, INV_TYPE, CONDITION) VALUES (4, 'Watercooler', 'Needs repairing/replacement');


-- Populating the Maintenance Requests table

-- Insert Record 1
INSERT INTO MAINTENANCE_REQUESTS (
    HOSTEL_ID, REQUEST_DATE, REQ_DESCRIPTION, ERP_ID, REQUEST_STATUS
) VALUES (
    1, 
    TO_DATE('2024-11-05', 'YYYY-MM-DD'), 
    'Broken chair in the study room.', 
    1001, 
    'Pending'
);

-- Insert Record 2
INSERT INTO MAINTENANCE_REQUESTS (
    HOSTEL_ID, REQUEST_DATE, REQ_DESCRIPTION, ERP_ID, REQUEST_STATUS
) VALUES (
    2, 
    TO_DATE('2024-11-10', 'YYYY-MM-DD'), 
    'Leakage in the bathroom sink.', 
    1023, 
    'In-Process'
);

-- Insert Record 3
INSERT INTO MAINTENANCE_REQUESTS (
    HOSTEL_ID, REQUEST_DATE, REQ_DESCRIPTION, ERP_ID, REQUEST_STATUS
) VALUES (
    3, 
    TO_DATE('2024-11-15', 'YYYY-MM-DD'), 
    'Electrical outlet not functioning in the common area.', 
    1060, 
    'Completed'
);

-- Insert Record 4
INSERT INTO MAINTENANCE_REQUESTS (
     HOSTEL_ID, REQUEST_DATE, REQ_DESCRIPTION, ERP_ID, REQUEST_STATUS
) VALUES (
    4, 
    TO_DATE('2024-11-20', 'YYYY-MM-DD'), 
    'Water cooler in the lounge is not dispensing water.', 
    1111, 
    'Pending'
);

-- Insert Record 5
INSERT INTO MAINTENANCE_REQUESTS (
    HOSTEL_ID, REQUEST_DATE, REQ_DESCRIPTION, ERP_ID, REQUEST_STATUS
) VALUES (
    1, 
    TO_DATE('2024-11-25', 'YYYY-MM-DD'), 
    'Ceiling fan in the study room is making noise.', 
    1005, 
    'In-Process'
);


-- Creating a logging table that keeps track of completed maintenance requests
 --Inserting Records into the Logging Table:
 --Whenever a maintenance request is marked as 'Completed', insert a corresponding record into the MAINTENANCE_REQUESTS_LOG table.
-- testing 
UPDATE MAINTENANCE_REQUESTS
SET REQUEST_STATUS = 'Completed'
WHERE REQUEST_ID = 1;

-- Populating Visitor Logs table

-- Insert Visitor Record 1
INSERT INTO VISITOR_LOGS (
    VISITOR_NAME, 
    HOSTEL_ID, 
    ERP_ID, 
    VISIT_DATE
) VALUES (
    'Maaiz Ahmed', 
    1, 
    1001, 
    TO_DATE('2024-11-05', 'YYYY-MM-DD')
);

-- Insert Visitor Record 2
INSERT INTO VISITOR_LOGS (
    VISITOR_NAME, 
    HOSTEL_ID, 
    ERP_ID, 
    VISIT_DATE
) VALUES (
    'Bilal Ahmed', 
    2, 
    1027, 
    TO_DATE('2024-11-10', 'YYYY-MM-DD')
);

-- Insert Visitor Record 3
INSERT INTO VISITOR_LOGS (
    VISITOR_NAME, 
    HOSTEL_ID, 
    ERP_ID, 
    VISIT_DATE
) VALUES (
    'Fatima Ali', 
    3, 
    1077, 
    TO_DATE('2024-11-15', 'YYYY-MM-DD')
);

-- Insert Visitor Record 4
INSERT INTO VISITOR_LOGS (
    VISITOR_NAME, 
    HOSTEL_ID, 
    ERP_ID, 
    VISIT_DATE
) VALUES (
    'Imran Sheikh', 
    4, 
    1109, 
    TO_DATE('2024-11-20', 'YYYY-MM-DD')
);

-- Insert Visitor Record 5
INSERT INTO VISITOR_LOGS (
    VISITOR_NAME, 
    HOSTEL_ID, 
    ERP_ID, 
    VISIT_DATE
) VALUES (
    'Saqlain Mushtaq', 
    1, 
    1009, 
    TO_DATE('2024-11-25', 'YYYY-MM-DD')
);

/* updating the checkout time of the visitors logged */
BEGIN
    update_checkout_time(2);
END;

BEGIN
    update_checkout_time(5);
END;

/* rooms table occupancy update hogi, trigger lag sakta hai */
select * from visitor_logs;


commit;